### ISSUE TITLE
typing_extensions (for python3.9) is required

### ISSUE THREAD

**Issue by animemoeus** [BombDash/BombDash-server#2]
```
(env) arter@animemoeus:~/bombsquad/BombDash-server$ ./configure.py build-debug
$ mkdir -p build
$ cd ballistica && git pull
Already up to date.
$ cp -rf ../src/* ballistica/assets/src/ba_data/
$ echo '{"license_line_checks": false}' > ballistica/config/localconfig.json
$ ballistica/tools/pcommand install_pip_reqs
Collecting pylint
  Using cached pylint-2.12.2-py3-none-any.whl (414 kB)
Collecting mypy
  Using cached mypy-0.920-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (24.6 MB)
Collecting yapf
  Using cached yapf-0.31.0-py2.py3-none-any.whl (185 kB)
Collecting cpplint
  Using cached cpplint-1.5.5-py3-none-any.whl (77 kB)
Collecting pytest
  Using cached pytest-6.2.5-py3-none-any.whl (280 kB)
Collecting pytz
  Using cached pytz-2021.3-py2.py3-none-any.whl (503 kB)
Collecting ansiwrap
  Using cached ansiwrap-0.8.4-py2.py3-none-any.whl (8.5 kB)
Collecting PyYAML
  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting typing_extensions
  Using cached typing_extensions-4.0.1-py3-none-any.whl (22 kB)
Collecting types-filelock
  Using cached types_filelock-3.2.1-py3-none-any.whl (2.3 kB)
Collecting types-requests
  Using cached types_requests-2.26.2-py3-none-any.whl (22 kB)
Collecting types-pytz
  Using cached types_pytz-2021.3.3-py3-none-any.whl (3.2 kB)
Collecting types-PyYAML
  Using cached types_PyYAML-6.0.1-py3-none-any.whl (13 kB)
Collecting astroid<2.10,>=2.9.0
  Using cached astroid-2.9.0-py3-none-any.whl (250 kB)
Collecting platformdirs>=2.2.0
  Using cached platformdirs-2.4.0-py3-none-any.whl (14 kB)
Collecting isort<6,>=4.2.5
  Using cached isort-5.10.1-py3-none-any.whl (103 kB)
Collecting toml>=0.9.2
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting mccabe<0.7,>=0.6
  Using cached mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting mypy-extensions<0.5.0,>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting tomli<3.0.0,>=1.1.0
  Using cached tomli-2.0.0-py3-none-any.whl (12 kB)
Collecting attrs>=19.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 197 kB/s 
Collecting pluggy<2.0,>=0.12
  Using cached pluggy-1.0.0-py2.py3-none-any.whl (13 kB)
Collecting py>=1.8.2
  Using cached py-1.11.0-py2.py3-none-any.whl (98 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting packaging
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting textwrap3>=0.9.2
  Using cached textwrap3-0.9.2-py2.py3-none-any.whl (12 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 6.7 MB/s 
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 11.7 MB/s 
Collecting idna<4,>=2.5; python_version >= "3"
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 375 kB/s 
Collecting charset-normalizer~=2.0.0; python_version >= "3"
  Using cached charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Requirement already satisfied, skipping upgrade: setuptools>=20.0 in /home/arter/bombsquad/BombDash-server/env/lib/python3.9/site-packages (from astroid<2.10,>=2.9.0->pylint) (44.0.0)
Collecting lazy-object-proxy>=1.4.0
  Using cached lazy_object_proxy-1.7.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61 kB)
Collecting wrapt<1.14,>=1.11
  Using cached wrapt-1.13.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (81 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.6-py3-none-any.whl (97 kB)
Installing collected packages: typing-extensions, lazy-object-proxy, wrapt, astroid, platformdirs, isort, toml, mccabe, pylint, mypy-extensions, tomli, mypy, yapf, cpplint, attrs, pluggy, py, iniconfig, pyparsing, packaging, pytest, pytz, textwrap3, ansiwrap, PyYAML, urllib3, certifi, idna, charset-normalizer, requests, types-filelock, types-requests, types-pytz, types-PyYAML
Successfully installed PyYAML-6.0 ansiwrap-0.8.4 astroid-2.9.0 attrs-21.2.0 certifi-2021.10.8 charset-normalizer-2.0.9 cpplint-1.5.5 idna-3.3 iniconfig-1.1.1 isort-5.10.1 lazy-object-proxy-1.7.1 mccabe-0.6.1 mypy-0.920 mypy-extensions-0.4.3 packaging-21.3 platformdirs-2.4.0 pluggy-1.0.0 py-1.11.0 pylint-2.12.2 pyparsing-3.0.6 pytest-6.2.5 pytz-2021.3 requests-2.26.0 textwrap3-0.9.2 toml-0.10.2 tomli-2.0.0 types-PyYAML-6.0.1 types-filelock-3.2.1 types-pytz-2021.3.3 types-requests-2.26.2 typing-extensions-4.0.1 urllib3-1.26.7 wrapt-1.13.3 yapf-0.31.0
All pip requirements installed!
$ cd ballistica && make update
Checking environment...
typing_extensions (for python3.9) is required.
To install it, try: "python3.9 -m pip install typing_extensions"
Alternately, "tools/pcommand install_pip_reqs" will update all pip requirements.
make: *** [Makefile:948: .cache/checkenv] Error 1
Traceback (most recent call last):
  File "/home/arter/bombsquad/BombDash-server/./configure.py", line 52, in <module>
    build('debug')
  File "/home/arter/bombsquad/BombDash-server/./configure.py", line 35, in build
    run(f'cd ballistica && make update')
  File "/home/arter/bombsquad/BombDash-server/./configure.py", line 18, in run
    raise RuntimeError(f'Process `{cmd}` exited with code {errno}')
RuntimeError: Process `cd ballistica && make update` exited with code 2
(env) arter@animemoeus:~/bombsquad/BombDash-server$
```

OS: Ubuntu 20.04.3 LTS x86_64

**Comment by animemoeus** [comment]
Solution: [https://github.com/efroemling/ballistica/issues/345#issuecomment-990992881](https://github.com/efroemling/ballistica/issues/345#issuecomment-990992881)
